/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ['@rdlabo/rules'],
  rules: {
    '@rdlabo/rules/deny-constructor-di': 'error',
    '@rdlabo/rules/deny-element': 'error',
    '@rdlabo/rules/deny-import-from-ionic-module': 'error',
    '@rdlabo/rules/deny-soft-private-modifier': 'error',
    '@rdlabo/rules/implements-ionic-lifecycle': 'error',
    '@rdlabo/rules/import-inject-object': 'error',
  },
};
