import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { ESLint } from 'eslint';

const filePath = resolve(__dirname, '../../src/configs/recommended.ts');

/**
 * Fleet-common @rdlabo/rules preset (Ionic + Angular).
 * Kept as an explicit template (not derived from meta.docs.recommended)
 * so options and ts/html file-glob splits stay correct.
 */
const rawContent = `/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

import type { Linter } from 'eslint';

/**
 * Flat ESLint recommended preset for Ionic + Angular fleet apps.
 * Spread via \`extends: [...rdlabo.configs.recommended]\` after registering the plugin.
 */
const recommended: Linter.Config[] = [
  {
    name: '@rdlabo/rules/recommended/typescript',
    files: ['**/*.ts'],
    rules: {
      '@rdlabo/rules/signal-use-as-signal': 'error',
      '@rdlabo/rules/signal-use-as-signal-template': 'error',
      '@rdlabo/rules/deny-import-from-ionic-module': 'error',
      '@rdlabo/rules/implements-ionic-lifecycle': 'error',
      '@rdlabo/rules/deny-soft-private-modifier': 'error',
      '@rdlabo/rules/deny-overlay-create': 'error',
      '@rdlabo/rules/prefer-modal-launcher': 'error',
      '@rdlabo/rules/require-viewmodel': 'error',
      '@rdlabo/rules/component-property-use-readonly': ['error', { ignorePrivateProperties: true }],
      '@rdlabo/rules/no-component-method-except-lifecycle': 'error',
    },
  },
  {
    name: '@rdlabo/rules/recommended/template',
    files: ['**/*.html'],
    rules: {
      '@rdlabo/rules/ionic-attr-type-check': 'error',
      '@rdlabo/rules/deny-element': [
        'error',
        {
          elements: ['ion-modal', 'ion-toast', 'ion-alert', 'ion-loading', 'ion-picker', 'ion-action-sheet'],
        },
      ],
    },
  },
];

export = recommended;
`;

const engine = new ESLint({ fix: true });
engine.lintText(rawContent, { filePath }).then((lintResult) => {
  const content = lintResult[0].output || rawContent;
  writeFileSync(filePath, content);
});
