/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: require('./configs/recommended'),
  },
  rules: {
    'deny-constructor-di': require('./rules/deny-constructor-di'),
    'deny-element': require('./rules/deny-element'),
  },
};
