/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

import recommended from './configs/recommended';

import denyConstructorDi from './rules/deny-constructor-di';
import denyElement from './rules/deny-element';
import denyImportFromIonicModule from './rules/deny-import-from-ionic-module';
import denySoftPrivateModifier from './rules/deny-soft-private-modifier';
import implementsIonicLifecycle from './rules/implements-ionic-lifecycle';
import signalUseAsSignal from './rules/signal-use-as-signal';
import signalUseAsSignalTemplate from './rules/signal-use-as-signal-template';
import propertyUseReadonly from './rules/property-use-readonly';

export = {
  meta: {
    name: '@rdlabo/rules',
  },
  configs: {
    recommended,
  },
  rules: {
    'deny-constructor-di': denyConstructorDi,
    'deny-element': denyElement,
    'deny-import-from-ionic-module': denyImportFromIonicModule,
    'deny-soft-private-modifier': denySoftPrivateModifier,
    'implements-ionic-lifecycle': implementsIonicLifecycle,
    'signal-use-as-signal': signalUseAsSignal,
    'signal-use-as-signal-template': signalUseAsSignalTemplate,
    'property-use-readonly': propertyUseReadonly,
  },
};
